import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'cat_food': 'Food',
      'cat_transport': 'Transport',
      'cat_housing': 'Housing',
      'cat_bills': 'Bills',
      'cat_shopping': 'Shopping',
      'cat_health': 'Health',
      'cat_education': 'Education',
      'cat_entertainment': 'Entertainment',
      'cat_family': 'Family',
      'cat_savings': 'Savings',
      'cat_emergency': 'Emergency',
      'cat_other': 'Other',
      'freq_daily': 'Daily',
      'freq_weekly': 'Weekly',
      'freq_monthly': 'Monthly',
      'freq_yearly': 'Yearly',
      'next_date': 'Next Execution Date',
      'amount_required': 'Please enter a valid amount',
      'monthly_limit': 'Monthly Limit',
      'category_name': 'Category Name',
      'select_source': 'Please select a source',
      'source_name': 'Source Name',
      'not_set': 'Not set',
      'placeholder': 'Select or enter value...',
      'select_placeholder': 'Select an option...',
      'template': 'Template',
      'TEMPLATE': 'TEMPLATE',
      'templates': 'Templates',
      'no_recurring_items': 'No Recurring Obligations',
      'recurring_desc': 'Set up recurring bills, subscriptions, or salaries to track them automatically.',
      'no_active_budgets': 'No Active Budgets',
      'budget_desc': 'Set monthly spending limits for categories to manage your finances.',
      'debt': 'Debt',
      'bills': 'Bills',
      'savings': 'Savings',
      'smart_recommendation': 'Smart Recommendation',
      'toggle_balance_privacy': 'Toggle Balance Privacy',
      'saved': 'Saved successfully',
      'type': 'Type',
      'view': 'View',
      'enter_name': 'Enter Name',
      'enter_amount': 'Enter Amount',
      'invalid_amount': 'Invalid amount',
      'app_title': 'Follow My Life',
      'app_tagline': 'Finance Intelligence OS',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'dashboard': 'Dashboard',
      'home': 'Home',
      'activity': 'Activity',
      'transactions': 'Transactions',
      'plan': 'Plan',
      'plans': 'Purchase & Savings Plans',
      'profile': 'Profile',
      'debts': 'Debts & Loans',
      'forecast': 'Cash-Flow Forecast',
      'calendar': 'Financial Calendar',
      'monthly_review': 'Monthly Review',
      'reports': 'Reports & Analytics',
      'categories': 'Categories',
      'budgets': 'Budgets',
      'recurring': 'Recurring Payments',
      'sources': 'Money Sources',
      'health_score': 'Financial Health Score',
      'emergency_reserve': 'Emergency Safety Reserve',
      'net_worth': 'Net Worth',
      'total_balance': 'Total Balance',
      'available_balance': 'Available Balance',
      'reserved_balance': 'Reserved Balance',
      'safe_to_spend': 'Safe to Spend',
      'safe_to_spend_breakdown': 'Safe-to-Spend Breakdown',
      'safe_to_spend_desc': 'Safe-to-spend tells you how much money you can safely spend today without risking upcoming bills, plan targets, or safety buffer.',
      'safe_to_spend_today': 'SAFE TO SPEND TODAY',
      'money_coming': 'Money Coming',
      'money_going': 'Money Going',
      'recent_activity': 'Recent Activity',
      'view_all': 'View All',
      'accounts': 'Accounts',
      'expenses': 'Expenses',
      'due_on': 'Due',
      'add': 'Add',
      'add_income': 'Add Income',
      'add_expense': 'Add Expense',
      'transfer': 'Transfer',
      'add_source': 'Add Money Source',
      'add_category': 'Add Category',
      'add_budget': 'Add Budget',
      'add_recurring': 'Add Recurring',
      'add_purchase': 'Add Purchase Plan',
      'add_debt': 'Add Debt / Loan',
      'i_owe': 'I Owe (Liabilities)',
      'owed_to_me': 'Owed to Me (Receivables)',
      'total_debt_balance': 'Total Debt Balance',
      'total_receivables': 'Total Receivables',
      'pay_back': 'Pay Back',
      'collect': 'Collect',
      'record_payment': 'Record Repayment',
      'record_collection': 'Record Debt Collection',
      'no_active_debts': 'No active debts',
      'no_pending_receivables': 'No pending receivables',
      'no_debts_desc': 'You do not owe money to anyone right now.',
      'no_receivables_desc': 'Nobody owes you money right now.',
      'no_sources': 'No money sources yet',
      'no_sources_desc': 'Add cash, bank account, or wallet to start tracking.',
      'no_transactions': 'No transactions yet',
      'no_transactions_desc': 'Record your income or expenses to see activity here.',
      'no_plans': 'No planned purchases',
      'no_plans_desc': 'Plan your next big target, wishlist item, or savings goal.',
      'no_budgets': 'No budgets set',
      'no_budgets_desc': 'Set category limits to control your monthly spending.',
      'no_categories': 'No categories',
      'no_categories_desc': 'Create categories to organize your transactions.',
      'no_recurring': 'No recurring payments',
      'no_recurring_desc': 'Add subscriptions or regular bills to automate tracking.',
      'preferences': 'Preferences',
      'security': 'Security & Lock',
      'data': 'Data & Reset',
      'language': 'Language',
      'theme': 'Theme Mode',
      'currency': 'Primary Currency',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'manage_categories': 'Manage Categories',
      'manage_budgets': 'Manage Budgets',
      'manage_recurring': 'Manage Recurring',
      'app_lock': 'Security PIN & Biometrics',
      'data_privacy': 'Data Privacy',
      'backup_restore': 'Backup & Restore',
      'reset_data': 'Reset All App Data',
      'search': 'Search...',
      'all': 'All',
      'income': 'Income',
      'expense': 'Expense',
      'cancel': 'Cancel',
      'save': 'Save',
      'submit': 'Submit',
      'edit': 'Edit',
      'delete': 'Delete',
      'due_date': 'Due Date',
      'amount': 'Amount',
      'note': 'Note',
      'description': 'Description',
      'category': 'Category',
      'source': 'Account / Source',
      'priority': 'Priority',
      'status': 'Status',
      'recalculate_balance': 'Recalculate Balance',
      'balance_recalculated': 'Balance recalculated',
      'confirm_delete': 'Confirm Deletion',
      'confirm_delete_msg': 'Are you sure you want to delete this item? This action cannot be undone.',
      'loading': 'Loading...',
      'error': 'Error',
      'something_went_wrong': 'Something went wrong. Please try again.',
      'cash': 'Cash',
      'bank_account': 'Bank Account',
      'e_wallet': 'E-Wallet',
      'income_source': 'Income Source',
      'other': 'Other',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'set_pin_title': 'Set Security PIN',
      'enter_pin_title': 'Enter PIN',
      'confirm_pin_title': 'Confirm Security PIN',
      'pin_saved': 'Security PIN updated',
      'pin_incorrect': 'Incorrect PIN. Try again.',
      'pin_too_many_attempts': 'Too many failed attempts. Throttled.',
      'lockout_active': 'Security lockout active. Please wait.',
      'auth_required_title': 'Authentication Required',
      'auth_required_desc': 'Please enter your PIN to modify security settings.',
      'color_preset': 'Accent & Gradient Theme',
      'theme_color': 'Theme Palette',
      'pin_disabled': 'Security PIN disabled',
      'data_cleared': 'All application data has been wiped.',
      'virtual_splits': 'Salary & Fund Allocation',
      'virtual_split': 'Virtual Split',
      'create_split': 'Create Virtual Split',
      'split_name': 'Split Name',
      'allocated': 'Allocated',
      'unallocated': 'Unallocated',
      'original_balance': 'Original Available Balance',
      'remaining_unallocated': 'Remaining Unallocated',
      'apply_split': 'Apply Split',
      'confirm_apply_split': 'Are you sure you want to apply this virtual split? This will commit actual transactions to your ledger.',
      'split_applied_success': 'Virtual split successfully applied!',
      'split_already_applied': 'This virtual split has already been applied.',
      'insufficient_funds_split': 'Insufficient available funds to apply this split.',
      'biometrics': 'Biometric Authentication (Fingerprint / Face)',
      'enable_biometrics': 'Enable Biometrics',
      'biometrics_not_available': 'Biometric authentication is unavailable on this device.',
      'biometrics_failed': 'Fingerprint not recognized. Try again or use PIN.',
      'biometric_auth_reason': 'Authenticate to unlock Follow My Life',
      'unlock': 'Unlock App',
      'total_planned_targets': 'Total Planned Targets',
      'items': 'Items',
      'reserved': 'Reserved',
      'remaining': 'Remaining',
      'emergency_reserve_target': 'Emergency Safety Reserve Target',
      'emergency_reserve_desc': 'Recommended safety buffer: 3 to 6 months of living expenses.',
      'can_buy_now': 'Can buy now with available funds',
      'needs_more': 'Needs more funds',
      'buy_now': 'Buy Now',
      'reserve_funds': 'Reserve Funds',
      'money_locations': 'Money Locations',
      'reconciled': 'Reconciled',
      'upcoming_obligations': 'Upcoming Obligations',
      'no_recent_activity': 'No recent activity',
      'net_cash_flow': 'Net Cash Flow',
      'required_monthly': 'Required Monthly',
      'est_completion': 'Est. Completion',
      'feasibility': 'Feasibility',
      'high_feasibility': 'Highly Achievable',
      'medium_feasibility': 'Moderate Effort',
      'low_feasibility': 'Challenging Deadline',
      'capacity_simulator': 'Capacity Simulator',
      'simulate_monthly_savings': 'Simulate Monthly Savings',
      'smart_actions_title': 'Smart Financial Assistant',
      'all_clear_title': 'All Clear',
      'all_clear_desc': 'Your finances look healthy and on track.',
      'fingerprint_enabled': 'Fingerprint security enabled',
      'fingerprint_disabled': 'Fingerprint security disabled',
      'profile_name_updated': 'Name updated successfully',
      'language_updated': 'Language updated successfully',
      'theme_updated': 'Theme updated successfully',
      'currency_updated': 'Currency updated successfully',
      'edit_profile_name': 'Edit Profile Name',
      'export_backup': 'Export Backup',
      'import_backup': 'Import Backup',
      'backup_export_saved': 'Backup export saved successfully.',
      'backup_imported': 'Database restored successfully.',
      'setup_profile': 'Setup Profile',
      'pin_active': 'Active (PIN)',
      'pin_off': 'Off',
      'data_protected': 'Protected',
      'data_encrypted_local': 'Data stays encrypted locally on device.',
      'error_loading_profile': 'Error loading profile',
      'enter_4_digit_pin': 'Enter 4-digit PIN',
      'failed_load_summary': 'Failed to load summary',
      'error_loading_transactions': 'Error loading transactions',
      'monthly_financial_review': 'Monthly Financial Review',
      'monthly_review_summary': 'Monthly Review Summary',
      'monthly_review_desc': 'Consolidated evaluation of your cash flow, savings rate, and financial health score.',
      'health_score_label': 'Health Score',
      'total_income': 'Total Income',
      'total_expenses': 'Total Expenses',
      'net_savings': 'Net Savings',
      'savings_rate': 'Savings Rate',
      'error_loading_summary': 'Error loading summary',
      'income_vs_expenses': 'Income vs Expenses',
      'spending_by_category': 'Spending by Category',
      'no_category_data': 'No expense category data for this period.',
      'error_loading_categories': 'Error loading category breakdown',
      'this_year': 'This Year',
      'vs_last_month': 'vs last month',
      'daily_budget': 'Daily Budget',
      'days_left': 'days left',
      'spending_pace': 'Spending Pace',
      'on_track': 'On track',
      'over_budget': 'Over budget',
      'under_budget': 'Under budget',
      'more_tools': 'More',
      'salary_allocation': 'Salary Allocation',
      'allocate_salary': 'Allocate Salary',
      'fund_distribution': 'Fund Distribution',
      'action_cash_deficit_title': 'Impending Cash Deficit Risk',
      'action_cash_deficit_desc': 'Upcoming bills and debt commitments exceed available balance.',
      'action_budget_exceeded_title': 'Budget Limit Exceeded',
      'action_budget_exceeded_desc': 'One or more of your active categories have exceeded target limits.',
      'action_split_pending_title': 'Active Salary Allocation Pending',
      'action_split_pending_desc': 'You have active pre-spending allocations ready for execution.',
      'action_sub_renewal_title': 'Upcoming Subscription Renewal',
      'action_plan_boost_title': 'Optimize Goal Savings',
      'action_plan_boost_desc': 'You have a healthy positive cash flow this month. Boost your priority plans.',
      'plan_name': 'Plan Name',
      'priority_low': 'Low',
      'priority_medium': 'Medium',
      'priority_high': 'High',
      'edit_recurring': 'Edit Recurring Payment',
      'delete_recurring': 'Delete Recurring Payment',
      'edit_category': 'Edit Category',
      'delete_category': 'Delete Category',
      'edit_source': 'Edit Money Source',
      'delete_source': 'Delete Money Source',
      'theme_mode': 'Appearance / Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'system_mode': 'System Default',
      'cash_flow_forecast': 'Cash-Flow Forecast',
      'projected_balance': 'Projected Balance',
      'days': 'Days',
      'net_change': 'Net Change',
      'forecast_timeline': 'Forecast Timeline',
      'no_movements': 'No scheduled movements',
      'from': 'From',
      'to': 'To',
      'date': 'Date',
      'note_optional': 'Note (Optional)',
      'need_2_sources': 'You need at least 2 sources to transfer money',
      'please_select_both_sources': 'Please select both sources',
      'same_source_error': 'Cannot transfer to the same source',
      'transaction_details': 'Transaction Details',
      'record_linked_refund': 'Record Linked Refund',
      'delete_transaction_confirm': 'This action will revert its effect on your balance. Are you sure?',
      'record_refund': 'Record Refund',
      'original_expense': 'Original Expense',
      'submit_refund': 'Submit Refund',
      'backup_json_desc': 'Create a safe encrypted JSON backup of your financial ledger or restore from file.',
      'money_account': 'Money Account',
      'income_origin': 'Income Origin',
      'payee_merchant': 'Payee / Merchant',
      'no_description': 'No description',
      'source_reference': 'Source Reference',
      'itemized_splits': 'Itemized Splits',
      'refund_amount': 'Refund Amount',
      'estimated_cost': 'Estimated Cost',
      'select_destination_source': 'Please select a destination source',
      'need_source_first': 'You need a money source first',
      'title_description': 'Title / Description',
      'to_source': 'To Source',
      'paid_from': 'Paid from',
      'what_was_this_for': 'What was this for?',
      'source_details': 'Source Details',
      'initial_balance': 'Initial Balance',
      'subscription_bill_name': 'Subscription/Bill Name',
      'income_name': 'Income Name',
      'auto_post_source': 'Auto-post to Source (Optional)',
      'none_remind_me': 'None (Remind me)',
      'plan_capacity_simulator': 'Plan Capacity Simulator',
      'simulator_desc': 'Enter your monthly savings capacity to see how it distributes across your active plans.',
      'monthly_savings_capacity': 'Monthly Savings Capacity',
      'simulate_capacity': 'Simulate Capacity',
      'optimal_allocation': 'Optimal Allocation',
      'close': 'Close',
      'delete_item_title': 'Delete Item',
      'delete_item_confirm': 'Are you sure you want to delete this item? This action cannot be undone.',
      'item_deleted': 'Item deleted successfully',
      'item_not_found': 'Item not found',
      'welcome_title': 'Welcome to\nFollow My Life',
      'welcome_subtitle': 'Your personal control center. Let\'s start by setting up your profile.',
      'onboarding_name_label': 'What should we call you?',
      'get_started': 'Get Started',
      'unlocked': 'Unlocked',
      'filter_all': 'All',
      'filter_ready': 'Ready',
      'target_date_label': 'Target',
      'target_date_optional': 'Target Date (Optional)',
      'clear_date': 'Clear Date',
      'error_loading_plans': 'Error loading plans',
      'error_loading_debts': 'Error loading debts',
      'error_loading_recurring': 'Error loading recurring items',
      'error_loading_sources': 'Error loading sources',
      'error_loading_budgets': 'Error loading budgets',
      'error_loading_splits': 'Error loading splits',
      'reserved_amount': 'Reserved Amount',
      'reserved_amount_updated': 'Reserved amount updated',
      'purchase_completed': 'Purchase completed!',
      'plan_updated': 'Plan updated',
      'per_month': '/mo',
      'plan_purchase': 'Plan Purchase',
      'purchase_name_label': 'What do you want to buy?',
      'create_budget': 'Create Budget',
      'budget_name': 'Budget Name',
      'budget_name_hint': 'e.g. Groceries, Entertainment',
      'limit_amount': 'Limit Amount',
      'period': 'Period',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'link_category_optional': 'Link to Category (Optional)',
      'none_general_budget': 'None (General Budget)',
      'i_owe_someone': 'I Owe Someone',
      'someone_owes_me': 'Someone Owes Me',
      'debt_person_hint': 'e.g. Karim, Bank Loan, Ahmed',
      'principal_amount': 'Principal Amount',
      'repayment_date_label': 'Expected Repayment / Due Date (Optional)',
      'notes_optional': 'Notes or Terms (Optional)',
      'debt_created': 'Debt/Loan record created',
      'income_origin_hint': 'e.g. Salary, Freelance',
      'extra_details_hint': 'Any extra details',
      'payee_hint': 'e.g. Coffee, Groceries',
      'source_name_hint': 'e.g. My Wallet, BNA Bank',
      'retry': 'Retry',
      'party_label': 'Party',
      'original_label': 'Original',
      'remaining_label': 'Remaining',
      'invalid_amount_source': 'Please enter a valid amount and account source',
      'debt_payment_recorded': 'Debt payment recorded successfully!',
      'split_description': 'Pre-allocate your available money across target categories before spending.',
      'split_cancelled': 'Virtual split cancelled',
      'split_exceeds_balance': 'Total split amount exceeds available balance!',
      'select_category_required': 'Please select a category for each item',
      'split_created': 'Virtual split created',
      'general': 'General',
      'default_user': 'User',
      'forecast_in': 'In',
      'forecast_out': 'Out',
      'upcoming_events': 'Upcoming Financial Events',
      'frequency': 'Frequency',
      'no_events_month': 'No scheduled events for this month',
      'skip': 'Skip',
      'next': 'Next',
      'onboarding_slide1_title': 'Total Financial Intelligence',
      'onboarding_slide1_desc': 'Track cash flows, money accounts, and smart allocations locally with zero cloud leakage.',
      'onboarding_slide2_title': 'Smart Virtual Splits',
      'onboarding_slide2_desc': 'Pre-allocate your income across envelopes before spending to guarantee emergency reserves.',
      'onboarding_slide3_title': 'Forecast & Purchasing Power',
      'onboarding_slide3_desc': 'Simulate monthly goal capacity and visualize future balance trends months in advance.',
      'onboarding_slide4_title': 'Set Up Your Private Ledger',
      'onboarding_slide4_desc': 'Enter your name to unlock your personalized financial operating system.',
      'page_not_found_desc': 'The page or route you requested does not exist or has been moved.',
      'simulation_calculated': 'Plan simulation updated successfully.',
      'tmpl_salary_50_20_20_10': 'Salary 50/20/20/10 Rule',
      'tmpl_salary_50_20_20_10_desc': '50% Needs, 20% Savings, 20% Plans & Goals, 10% Free Spending',
      'tmpl_classic_50_30_20': 'Classic 50/30/20 Rule',
      'tmpl_classic_50_30_20_desc': '50% Essential Needs, 30% Personal Wants, 20% Savings',
      'tmpl_monthly_essentials': 'Monthly Essentials Preset',
      'tmpl_monthly_essentials_desc': '40% Food & Groceries, 30% Utilities & Bills, 15% Transport, 15% Buffer',
      'tmpl_emergency_first': 'Emergency Reserve Priority',
      'tmpl_emergency_first_desc': '50% Emergency Reserve, 30% Living Costs, 20% Flexible',
      'tmpl_debt_paydown': 'Accelerated Debt Paydown',
      'tmpl_debt_paydown_desc': '40% Debt Repayment, 40% Living Essentials, 10% Savings, 10% Buffer',
      'tmpl_wealth_growth': 'Wealth Building & Investment',
      'tmpl_wealth_growth_desc': '40% Investments & Growth, 30% Core Expenses, 20% Cash Reserve, 10% Lifestyle',
      'tmpl_travel_vacation': 'Travel & Vacation Budget',
      'tmpl_travel_vacation_desc': '40% Lodging & Hotel, 30% Flights & Transit, 30% Activities & Dining',
      'tmpl_student_freelancer': 'Student & Freelancer Budget',
      'tmpl_student_freelancer_desc': '60% Basic Survival, 20% Work & Study Tools, 20% Future Buffer',
      'cat_needs_essentials': 'Needs & Essentials',
      'cat_savings_reserve': 'Savings & Reserve',
      'cat_plans_goals': 'Plans & Goals',
      'cat_free_spending': 'Free Spending',
      'cat_essential_needs': 'Essential Needs',
      'cat_personal_wants': 'Personal Wants',
      'cat_savings_investments': 'Savings & Investments',
      'cat_food_groceries': 'Food & Groceries',
      'cat_utilities_bills': 'Utilities & Bills',
      'cat_transport_fuel': 'Transport & Fuel',
      'cat_emergency_buffer': 'Emergency Buffer',
      'cat_emergency_reserve': 'Emergency Reserve',
      'cat_fixed_living': 'Fixed Living Costs',
      'cat_flexible_spending': 'Flexible Spending',
      'cat_debt_repayment': 'Debt Repayment',
      'cat_living_essentials': 'Living Essentials',
      'cat_investments_growth': 'Investments & Growth',
      'cat_core_expenses': 'Core Expenses',
      'cat_cash_reserve': 'Cash Reserve',
      'cat_lifestyle': 'Lifestyle',
      'cat_lodging_hotel': 'Lodging & Hotel',
      'cat_flights_transit': 'Flights & Transit',
      'cat_activities_dining': 'Activities & Dining',
      'cat_basic_survival': 'Basic Survival',
      'cat_work_study_tools': 'Work & Study Tools',
      'cat_future_buffer': 'Future Buffer',
      'delete_transaction': 'Delete Transaction',
      'split': 'Split',
      'amount_positive': 'Amount must be greater than zero.',
      'saved_successfully': 'Saved successfully.',
      'capacity_summary': 'Simulation Capacity Summary',
      'total_target_amount': 'Total Goal Target',
      'months_needed': 'Est. Time Needed',
      'fully_feasible': '100% Feasible & Fully Funded',
      'capacity_deficit': 'Partial Capacity Deficit',
      'no_plans_to_simulate': 'No active purchase plans found',
      'create_plan_first_desc': 'Create a purchase plan to track your real savings targets or simulate with a sample goal below.',
      'simulate_sample_plan': 'Simulate Sample Goal (100,000 DZD)',
      'sample_plan_title': 'Sample Savings Target',
    },
    'fr': {
      'cat_food': 'Alimentation',
      'cat_transport': 'Transport',
      'cat_housing': 'Logement',
      'cat_bills': 'Factures',
      'cat_shopping': 'Shopping',
      'cat_health': 'Santé',
      'cat_education': 'Éducation',
      'cat_entertainment': 'Divertissement',
      'cat_family': 'Famille',
      'cat_savings': 'Épargne',
      'cat_emergency': 'Urgence',
      'cat_other': 'Autre',
      'freq_daily': 'Quotidien',
      'freq_weekly': 'Hebdomadaire',
      'freq_monthly': 'Mensuel',
      'freq_yearly': 'Annuel',
      'next_date': 'Prochaine date',
      'amount_required': 'Veuillez saisir un montant valide',
      'monthly_limit': 'Limite mensuelle',
      'category_name': 'Nom de la catégorie',
      'select_source': 'Veuillez sélectionner une source',
      'source_name': 'Nom de la source',
      'not_set': 'Non défini',
      'placeholder': 'Sélectionner ou saisir une valeur...',
      'select_placeholder': 'Sélectionner une option...',
      'template': 'Modèle',
      'TEMPLATE': 'MODÈLE',
      'templates': 'Modèles',
      'no_recurring_items': 'Aucune obligation récurrente',
      'recurring_desc': 'Configurez des factures, abonnements ou salaires récurrents.',
      'no_active_budgets': 'Aucun budget actif',
      'budget_desc': 'Définissez des limites de dépenses mensuelles par catégorie.',
      'debt': 'Dette',
      'bills': 'Factures',
      'savings': 'Épargne',
      'smart_recommendation': 'Recommandation intelligente',
      'toggle_balance_privacy': 'Masquer/Afficher les soldes',
      'saved': 'Enregistré avec succès',
      'type': 'Type',
      'view': 'Voir',
      'enter_name': 'Entrer le nom',
      'enter_amount': 'Entrer le montant',
      'invalid_amount': 'Montant invalide',
      'app_title': 'Follow My Life',
      'app_tagline': 'OS d\'Intelligence Financière',
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'dashboard': 'Tableau de bord',
      'home': 'Accueil',
      'activity': 'Activité',
      'transactions': 'Transactions',
      'plan': 'Planification',
      'plans': 'Plans d\'achat et d\'épargne',
      'profile': 'Profil',
      'debts': 'Dettes & Prêts',
      'forecast': 'Prévision de trésorerie',
      'calendar': 'Calendrier financier',
      'monthly_review': 'Bilan mensuel',
      'reports': 'Rapports & Analyses',
      'categories': 'Catégories',
      'budgets': 'Budgets',
      'recurring': 'Paiements récurrents',
      'sources': 'Sources d\'argent',
      'health_score': 'Score de santé financière',
      'emergency_reserve': 'Réserve de sécurité',
      'net_worth': 'Valeur nette',
      'total_balance': 'Solde total',
      'available_balance': 'Solde disponible',
      'reserved_balance': 'Solde réservé',
      'safe_to_spend': 'Dépense sécurisée',
      'safe_to_spend_breakdown': 'Détail de la dépense sécurisée',
      'safe_to_spend_desc': 'La dépense sécurisée vous indique combien vous pouvez dépenser aujourd\'hui sans risquer vos factures à venir, vos objectifs ou votre réserve.',
      'safe_to_spend_today': 'DÉPENSE SÉCURISÉE AUJOURD\'HUI',
      'money_coming': 'Entrées prévues',
      'money_going': 'Sorties prévues',
      'recent_activity': 'Activité récente',
      'view_all': 'Tout voir',
      'accounts': 'Comptes',
      'expenses': 'Dépenses',
      'due_on': 'Échéance',
      'add': 'Ajouter',
      'add_income': 'Ajouter un revenu',
      'add_expense': 'Ajouter une dépense',
      'transfer': 'Transfert',
      'add_source': 'Ajouter une source',
      'add_category': 'Ajouter une catégorie',
      'add_budget': 'Ajouter un budget',
      'add_recurring': 'Ajouter un récurrent',
      'add_purchase': 'Ajouter un achat prévu',
      'add_debt': 'Ajouter dette / prêt',
      'i_owe': 'Je dois (Passif)',
      'owed_to_me': 'On me doit (Actif)',
      'total_debt_balance': 'Solde total des dettes',
      'total_receivables': 'Créances totales',
      'pay_back': 'Rembourser',
      'collect': 'Recouvrer',
      'record_payment': 'Enregistrer un remboursement',
      'record_collection': 'Enregistrer un encaissement',
      'no_active_debts': 'Aucune dette active',
      'no_pending_receivables': 'Aucune créance en attente',
      'no_debts_desc': 'Vous ne devez d\'argent à personne pour le moment.',
      'no_receivables_desc': 'Personne ne vous doit d\'argent actuellement.',
      'no_sources': 'Aucune source d\'argent',
      'no_sources_desc': 'Ajoutez du liquide, un compte bancaire ou un portefeuille.',
      'no_transactions': 'Aucune transaction',
      'no_transactions_desc': 'Enregistrez vos revenus ou dépenses pour voir l\'activité.',
      'no_plans': 'Aucun achat prévu',
      'no_plans_desc': 'Planifiez votre prochain objectif ou projet d\'achat.',
      'no_budgets': 'Aucun budget défini',
      'no_budgets_desc': 'Définissez des limites par catégorie pour suivre vos dépenses.',
      'no_categories': 'Aucune catégorie',
      'no_categories_desc': 'Créez des catégories pour organiser vos opérations.',
      'no_recurring': 'Aucun paiement récurrent',
      'no_recurring_desc': 'Ajoutez des abonnements ou factures régulières.',
      'preferences': 'Préférences',
      'security': 'Sécurité & Verrouillage',
      'data': 'Données & Réinitialisation',
      'language': 'Langue',
      'theme': 'Mode de thème',
      'currency': 'Devise principale',
      'light': 'Clair',
      'dark': 'Sombre',
      'system': 'Système',
      'manage_categories': 'Gérer les catégories',
      'manage_budgets': 'Gérer les budgets',
      'manage_recurring': 'Gérer les récurrences',
      'app_lock': 'Code PIN & Empreinte digitale',
      'data_privacy': 'Confidentialité des données',
      'backup_restore': 'Sauvegarde & Restauration',
      'reset_data': 'Réinitialiser toutes les données',
      'search': 'Rechercher...',
      'all': 'Tout',
      'income': 'Revenu',
      'expense': 'Dépense',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'submit': 'Soumettre',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'due_date': 'Date d\'échéance',
      'amount': 'Montant',
      'note': 'Note',
      'description': 'Description',
      'category': 'Catégorie',
      'source': 'Compte / Source',
      'priority': 'Priorité',
      'status': 'Statut',
      'recalculate_balance': 'Recalculer le solde',
      'balance_recalculated': 'Solde recalculé avec succès',
      'confirm_delete': 'Confirmer la suppression',
      'confirm_delete_msg': 'Êtes-vous sûr de vouloir supprimer cet élément ? Cette action est irréversible.',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'something_went_wrong': 'Une erreur est survenue. Veuillez réessayer.',
      'cash': 'Espèces',
      'bank_account': 'Compte bancaire',
      'e_wallet': 'Portefeuille électronique',
      'income_source': 'Source de revenu',
      'other': 'Autre',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'tomorrow': 'Demain',
      'this_month': 'Ce mois-ci',
      'last_month': 'Mois dernier',
      'set_pin_title': 'Définir le code PIN',
      'enter_pin_title': 'Entrer le code PIN',
      'confirm_pin_title': 'Confirmer le code PIN',
      'pin_saved': 'Code PIN mis à jour',
      'pin_incorrect': 'Code PIN incorrect.',
      'pin_too_many_attempts': 'Trop de tentatives échouées. Accès temporairement bloqué.',
      'lockout_active': 'Verrouillage de sécurité actif. Veuillez patienter.',
      'auth_required_title': 'Authentification requise',
      'auth_required_desc': 'Veuillez saisir votre code PIN pour modifier les paramètres de sécurité.',
      'color_preset': 'Thème de couleur et dégradé',
      'theme_color': 'Palette de couleurs',
      'pin_disabled': 'Code PIN désactivé',
      'data_cleared': 'Toutes les données ont été effacées.',
      'virtual_splits': 'Répartition du salaire et des fonds',
      'virtual_split': 'Répartition virtuelle',
      'create_split': 'Créer une répartition virtuelle',
      'split_name': 'Nom de la répartition',
      'allocated': 'Alloué',
      'unallocated': 'Non alloué',
      'original_balance': 'Solde initial disponible',
      'remaining_unallocated': 'Reste non alloué',
      'apply_split': 'Appliquer la répartition',
      'confirm_apply_split': 'Voulez-vous vraiment appliquer cette répartition virtuelle ? Des transactions réelles seront créées.',
      'split_applied_success': 'Répartition virtuelle appliquée avec succès !',
      'split_already_applied': 'Cette répartition virtuelle a déjà été appliquée.',
      'insufficient_funds_split': 'Fonds disponibles insuffisants pour appliquer cette répartition.',
      'biometrics': 'Authentification biométrique (Empreinte / Visage)',
      'enable_biometrics': 'Activer la biométrie',
      'biometrics_not_available': 'L\'authentification biométrique n\'est pas disponible sur cet appareil.',
      'biometrics_failed': 'Empreinte non reconnue. Réessayez ou utilisez le code PIN.',
      'biometric_auth_reason': 'Authentifiez-vous pour déverrouiller Follow My Life',
      'unlock': 'Déverrouiller l\'application',
      'total_planned_targets': 'Objectifs totaux planifiés',
      'items': 'Éléments',
      'reserved': 'Réservé',
      'remaining': 'Reste',
      'emergency_reserve_target': 'Objectif réserve de sécurité',
      'emergency_reserve_desc': 'Coussin de sécurité recommandé : 3 à 6 mois de dépenses.',
      'can_buy_now': 'Peut être acheté maintenant',
      'needs_more': 'Nécessite des fonds supplémentaires',
      'buy_now': 'Acheter maintenant',
      'reserve_funds': 'Réserver des fonds',
      'money_locations': 'Emplacements de l\'argent',
      'reconciled': 'Rapproché',
      'upcoming_obligations': 'Obligations à venir',
      'no_recent_activity': 'Aucune activité récente',
      'net_cash_flow': 'Flux de trésorerie net',
      'required_monthly': 'Mensuel requis',
      'est_completion': 'Achèvement estimé',
      'feasibility': 'Faisabilité',
      'high_feasibility': 'Très réalisable',
      'medium_feasibility': 'Effort modéré',
      'low_feasibility': 'Échéance difficile',
      'capacity_simulator': 'Simulateur de capacité',
      'simulate_monthly_savings': 'Simuler l\'épargne mensuelle',
      'smart_actions_title': 'Assistant financier intelligent',
      'all_clear_title': 'Tout est en ordre',
      'all_clear_desc': 'Vos finances sont saines et parfaitement maîtrisées.',
      'fingerprint_enabled': 'Sécurité par empreinte activée',
      'fingerprint_disabled': 'Sécurité par empreinte désactivée',
      'profile_name_updated': 'Nom mis à jour avec succès',
      'language_updated': 'Langue mise à jour avec succès',
      'theme_updated': 'Thème mis à jour avec succès',
      'currency_updated': 'Devise mise à jour avec succès',
      'edit_profile_name': 'Modifier le nom du profil',
      'export_backup': 'Exporter la sauvegarde',
      'import_backup': 'Importer la sauvegarde',
      'backup_export_saved': 'Sauvegarde exportée avec succès.',
      'backup_imported': 'Base de données restaurée avec succès.',
      'setup_profile': 'Créer un profil',
      'pin_active': 'Actif (PIN)',
      'pin_off': 'Désactivé',
      'data_protected': 'Protégé',
      'data_encrypted_local': 'Les données restent chiffrées localement sur l\'appareil.',
      'error_loading_profile': 'Erreur de chargement du profil',
      'enter_4_digit_pin': 'Entrez un PIN à 4 chiffres',
      'failed_load_summary': 'Échec du chargement du résumé',
      'error_loading_transactions': 'Erreur de chargement des transactions',
      'monthly_financial_review': 'Bilan financier mensuel',
      'monthly_review_summary': 'Résumé du bilan mensuel',
      'monthly_review_desc': 'Évaluation consolidée de votre flux de trésorerie, taux d\'épargne et score de santé financière.',
      'health_score_label': 'Score de santé',
      'total_income': 'Revenu total',
      'total_expenses': 'Dépenses totales',
      'net_savings': 'Épargne nette',
      'savings_rate': 'Taux d\'épargne',
      'error_loading_summary': 'Erreur de chargement du résumé',
      'income_vs_expenses': 'Revenus vs Dépenses',
      'spending_by_category': 'Dépenses par catégorie',
      'no_category_data': 'Aucune donnée de dépenses pour cette période.',
      'error_loading_categories': 'Erreur de chargement des catégories',
      'this_year': 'Cette année',
      'vs_last_month': 'vs mois dernier',
      'daily_budget': 'Budget quotidien',
      'days_left': 'jours restants',
      'spending_pace': 'Rythme de dépenses',
      'on_track': 'En bonne voie',
      'over_budget': 'Dépassement',
      'under_budget': 'Sous le budget',
      'more_tools': 'Plus',
      'salary_allocation': 'Répartition du salaire',
      'allocate_salary': 'Répartir le salaire',
      'fund_distribution': 'Distribution des fonds',
      'action_cash_deficit_title': 'Risque de déficit de trésorerie',
      'action_cash_deficit_desc': 'Les factures et engagements dépassent le solde disponible.',
      'action_budget_exceeded_title': 'Limite de budget dépassée',
      'action_budget_exceeded_desc': 'Une ou plusieurs catégories ont dépassé les limites fixées.',
      'action_split_pending_title': 'Répartition du salaire en attente',
      'action_split_pending_desc': 'Vous avez des allocations de dépenses à exécuter.',
      'action_sub_renewal_title': 'Renouvellement d\'abonnement imminent',
      'action_plan_boost_title': 'Optimiser vos objectifs d\'épargne',
      'action_plan_boost_desc': 'Flux de trésorerie positif. Augmentez vos épargnes prioritaires.',
      'plan_name': 'Nom du plan',
      'priority_low': 'Basse',
      'priority_medium': 'Moyenne',
      'priority_high': 'Haute',
      'edit_recurring': 'Modifier le paiement récurrent',
      'delete_recurring': 'Supprimer le paiement récurrent',
      'edit_category': 'Modifier la catégorie',
      'delete_category': 'Supprimer la catégorie',
      'edit_source': 'Modifier la source d\'argent',
      'delete_source': 'Supprimer la source d\'argent',
      'theme_mode': 'Apparence / Thème',
      'dark_mode': 'Mode Sombre',
      'light_mode': 'Mode Clair',
      'system_mode': 'Par défaut du système',
      'cash_flow_forecast': 'Prévision de trésorerie',
      'projected_balance': 'Solde projeté',
      'days': 'Jours',
      'net_change': 'Variation nette',
      'forecast_timeline': 'Chronologie des prévisions',
      'no_movements': 'Aucun mouvement prévu',
      'from': 'De',
      'to': 'Vers',
      'date': 'Date',
      'note_optional': 'Note (Optionnelle)',
      'need_2_sources': 'Vous avez besoin d\'au moins 2 sources pour transférer de l\'argent',
      'please_select_both_sources': 'Veuillez sélectionner les deux sources',
      'same_source_error': 'Impossible de transférer vers la même source',
      'transaction_details': 'Détails de la transaction',
      'record_linked_refund': 'Enregistrer un remboursement lié',
      'delete_transaction_confirm': 'Cette action annulera son effet sur votre solde. Êtes-vous sûr ?',
      'record_refund': 'Enregistrer un remboursement',
      'original_expense': 'Dépense originale',
      'submit_refund': 'Soumettre le remboursement',
      'backup_json_desc': 'Créez une sauvegarde JSON sécurisée ou restaurez à partir d\'un fichier.',
      'money_account': 'Compte d\'argent',
      'income_origin': 'Origine du revenu',
      'payee_merchant': 'Bénéficiaire / Commerçant',
      'no_description': 'Aucune description',
      'source_reference': 'Référence source',
      'itemized_splits': 'Ventilations détaillées',
      'refund_amount': 'Montant du remboursement',
      'estimated_cost': 'Coût estimé',
      'select_destination_source': 'Veuillez sélectionner une source de destination',
      'need_source_first': 'Vous devez d\'abord ajouter une source d\'argent',
      'title_description': 'Titre / Description',
      'to_source': 'Vers la source',
      'paid_from': 'Payé depuis',
      'what_was_this_for': 'À quoi cela a-t-il servi ?',
      'source_details': 'Détails de la source',
      'initial_balance': 'Solde initial',
      'subscription_bill_name': 'Nom de l\'abonnement/facture',
      'income_name': 'Nom du revenu',
      'auto_post_source': 'Publication auto sur la source (Optionnel)',
      'none_remind_me': 'Aucun (Me rappeler)',
      'plan_capacity_simulator': 'Simulateur de capacité du plan',
      'simulator_desc': 'Entrez votre capacité d\'épargne mensuelle pour voir comment elle se répartit entre vos plans actifs.',
      'monthly_savings_capacity': 'Capacité d\'épargne mensuelle',
      'simulate_capacity': 'Simuler la capacité',
      'optimal_allocation': 'Allocation optimale',
      'close': 'Fermer',
      'delete_item_title': 'Supprimer l\'élément',
      'delete_item_confirm': 'Êtes-vous sûr de vouloir supprimer cet élément ? Cette action est irréversible.',
      'item_deleted': 'Élément supprimé avec succès',
      'item_not_found': 'Élément introuvable',
      'welcome_title': 'Bienvenue sur\nFollow My Life',
      'welcome_subtitle': 'Votre centre de contrôle personnel. Commençons par créer votre profil.',
      'onboarding_name_label': 'Comment devons-nous vous appeler ?',
      'get_started': 'Commencer',
      'unlocked': 'Déverrouillé',
      'filter_all': 'Tous',
      'filter_ready': 'Prêt',
      'target_date_label': 'Objectif',
      'target_date_optional': 'Date cible (Optionnel)',
      'clear_date': 'Effacer la date',
      'error_loading_plans': 'Erreur de chargement des plans',
      'error_loading_debts': 'Erreur de chargement des dettes',
      'error_loading_recurring': 'Erreur de chargement des récurrences',
      'error_loading_sources': 'Erreur de chargement des sources',
      'error_loading_budgets': 'Erreur de chargement des budgets',
      'error_loading_splits': 'Erreur de chargement des répartitions',
      'reserved_amount': 'Montant réservé',
      'reserved_amount_updated': 'Montant réservé mis à jour',
      'purchase_completed': 'Achat effectué !',
      'plan_updated': 'Plan mis à jour',
      'per_month': '/mois',
      'plan_purchase': 'Planifier un achat',
      'purchase_name_label': 'Que voulez-vous acheter ?',
      'create_budget': 'Créer un budget',
      'budget_name': 'Nom du budget',
      'budget_name_hint': 'ex. Courses, Divertissement',
      'limit_amount': 'Montant limite',
      'period': 'Période',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'yearly': 'Annuel',
      'link_category_optional': 'Lier à une catégorie (Optionnel)',
      'none_general_budget': 'Aucune (Budget général)',
      'i_owe_someone': 'Je dois à quelqu\'un',
      'someone_owes_me': 'Quelqu\'un me doit',
      'debt_person_hint': 'ex. Karim, Prêt bancaire, Ahmed',
      'principal_amount': 'Montant principal',
      'repayment_date_label': 'Date de remboursement prévue (Optionnel)',
      'notes_optional': 'Notes ou conditions (Optionnel)',
      'debt_created': 'Enregistrement de dette/prêt créé',
      'income_origin_hint': 'ex. Salaire, Freelance',
      'extra_details_hint': 'Détails supplémentaires',
      'payee_hint': 'ex. Café, Courses',
      'source_name_hint': 'ex. Mon portefeuille, BNA Banque',
      'retry': 'Réessayer',
      'party_label': 'Partie',
      'original_label': 'Original',
      'remaining_label': 'Restant',
      'invalid_amount_source': 'Veuillez saisir un montant et une source valides',
      'debt_payment_recorded': 'Paiement de dette enregistré avec succès !',
      'split_description': 'Pré-répartissez votre argent disponible entre les catégories avant de dépenser.',
      'split_cancelled': 'Répartition virtuelle annulée',
      'split_exceeds_balance': 'Le montant total dépasse le solde disponible !',
      'select_category_required': 'Veuillez sélectionner une catégorie pour chaque élément',
      'split_created': 'Répartition virtuelle créée',
      'general': 'Général',
      'default_user': 'Utilisateur',
      'forecast_in': 'Entrée',
      'forecast_out': 'Sortie',
      'upcoming_events': 'Événements financiers à venir',
      'frequency': 'Fréquence',
      'no_events_month': 'Aucun événement prévu pour ce mois',
      'skip': 'Passer',
      'next': 'Suivant',
      'onboarding_slide1_title': 'Intelligence Financière Totale',
      'onboarding_slide1_desc': 'Gérez votre trésorerie, vos comptes et allocations localement en toute sécurité.',
      'onboarding_slide2_title': 'Allocations Intelligentes',
      'onboarding_slide2_desc': 'Pré-allouez vos revenus dans des enveloppes avant de dépenser pour vos réserves.',
      'onboarding_slide3_title': 'Prévisions & Capacité d\'Achat',
      'onboarding_slide3_desc': 'Simulez votre capacité d\'achat et visualisez l\'évolution du solde des mois à l\'avance.',
      'onboarding_slide4_title': 'Configurez Votre Journal Privé',
      'onboarding_slide4_desc': 'Entrez votre nom pour déverrouiller votre système d\'exploitation financier.',
      'page_not_found_desc': 'La page ou la route demandée n\'existe pas ou a été déplacée.',
      'simulation_calculated': 'Simulation du plan mise à jour avec succès.',
      'tmpl_salary_50_20_20_10': 'Règle Salaire 50/20/20/10',
      'tmpl_salary_50_20_20_10_desc': '50% Besoins, 20% Épargne, 20% Projets & Objectifs, 10% Dépenses Libres',
      'tmpl_classic_50_30_20': 'Règle Classique 50/30/20',
      'tmpl_classic_50_30_20_desc': '50% Besoins Essentiels, 30% Envies Personnelles, 20% Épargne',
      'tmpl_monthly_essentials': 'Modèle Essentiels Mensuels',
      'tmpl_monthly_essentials_desc': '40% Alimentation, 30% Factures & Logement, 15% Transport, 15% Réserve',
      'tmpl_emergency_first': 'Priorité Réserve de Secours',
      'tmpl_emergency_first_desc': '50% Réserve d\'Urgence, 30% Coûts de Vie, 20% Flexible',
      'tmpl_debt_paydown': 'Remboursement de Dette Accéléré',
      'tmpl_debt_paydown_desc': '40% Remboursement Dette, 40% Besoins Vitaux, 10% Épargne, 10% Réserve',
      'tmpl_wealth_growth': 'Investissement & Croissance',
      'tmpl_wealth_growth_desc': '40% Investissements, 30% Dépenses de Base, 20% Trésorerie, 10% Loisirs',
      'tmpl_travel_vacation': 'Budget Voyage & Vacances',
      'tmpl_travel_vacation_desc': '40% Hébergement, 30% Transport, 30% Activités & Repas',
      'tmpl_student_freelancer': 'Budget Étudiant & Indépendant',
      'tmpl_student_freelancer_desc': '60% Vital, 20% Outils de Travail/Études, 20% Réserve Future',
      'cat_needs_essentials': 'Besoins & Essentiels',
      'cat_savings_reserve': 'Épargne & Réserve',
      'cat_plans_goals': 'Projets & Objectifs',
      'cat_free_spending': 'Dépenses Libres',
      'cat_essential_needs': 'Besoins Essentiels',
      'cat_personal_wants': 'Envies Personnelles',
      'cat_savings_investments': 'Épargne & Investissements',
      'cat_food_groceries': 'Alimentation & Courses',
      'cat_utilities_bills': 'Factures & Charges',
      'cat_transport_fuel': 'Transport & Carburant',
      'cat_emergency_buffer': 'Réserve de Sécurité',
      'cat_emergency_reserve': 'Réserve d\'Urgence',
      'cat_fixed_living': 'Charges Fixes',
      'cat_flexible_spending': 'Dépenses Flexibles',
      'cat_debt_repayment': 'Remboursement Dette',
      'cat_living_essentials': 'Essentiels du Quotidien',
      'cat_investments_growth': 'Investissements',
      'cat_core_expenses': 'Dépenses Vitales',
      'cat_cash_reserve': 'Trésorerie Disponible',
      'cat_lifestyle': 'Style de Vie & Loisirs',
      'cat_lodging_hotel': 'Hébergement & Hôtel',
      'cat_flights_transit': 'Vols & Transports',
      'cat_activities_dining': 'Activités & Repas',
      'cat_basic_survival': 'Besoins Vitaux',
      'cat_work_study_tools': 'Outils & Études',
      'cat_future_buffer': 'Réserve Future',
      'delete_transaction': 'Supprimer la Transaction',
      'split': 'Ventilation',
      'amount_positive': 'Le montant doit être supérieur à zéro.',
      'saved_successfully': 'Enregistré avec succès.',
      'capacity_summary': 'Résumé de la Simulation',
      'total_target_amount': 'Cible Totale des Objectifs',
      'months_needed': 'Temps Estimé Requis',
      'fully_feasible': '100% Faisable & Entièrement Financé',
      'capacity_deficit': 'Déficit Partiel de Capacité',
      'no_plans_to_simulate': 'Aucun plan d\'achat actif trouvé',
      'create_plan_first_desc': 'Créez un projet d\'achat pour suivre vos objectifs réels ou simulez avec l\'objectif exemple ci-dessous.',
      'simulate_sample_plan': 'Simuler un Objectif Exemple (100 000 DZD)',
      'sample_plan_title': 'Objectif d\'Épargne Exemple',
    },
    'ar': {
      'cat_food': 'طعام',
      'cat_transport': 'نقل',
      'cat_housing': 'سكن',
      'cat_bills': 'فواتير',
      'cat_shopping': 'تسوق',
      'cat_health': 'صحة',
      'cat_education': 'تعليم',
      'cat_entertainment': 'ترفيه',
      'cat_family': 'عائلة',
      'cat_savings': 'مدخرات',
      'cat_emergency': 'طوارئ',
      'cat_other': 'أخرى',
      'freq_daily': 'يومي',
      'freq_weekly': 'أسبوعي',
      'freq_monthly': 'شهري',
      'freq_yearly': 'سنوي',
      'next_date': 'تاريخ التنفيذ القادم',
      'amount_required': 'يرجى إدخال مبلغ صحيح',
      'monthly_limit': 'الحد الشهري',
      'category_name': 'اسم الفئة',
      'select_source': 'الرجاء اختيار المصدر',
      'source_name': 'اسم المصدر',
      'not_set': 'لم يحدد',
      'placeholder': 'اختر أو أدخل قيمة...',
      'select_placeholder': 'اختر خيارًا...',
      'template': 'قالب',
      'TEMPLATE': 'قالب',
      'templates': 'القوالب',
      'no_recurring_items': 'لا توجد التزامات متكررة',
      'recurring_desc': 'قم بإعداد الفواتير أو الاشتراكات أو الرواتب المتكررة لمتابعتها تلقائيًا.',
      'no_active_budgets': 'لا توجد ميزانيات نشطة',
      'budget_desc': 'حدد حدود الإنفاق الشهرية للفئات لإدارة ميزانيتك.',
      'debt': 'دين',
      'bills': 'فواتير',
      'savings': 'مدخرات',
      'smart_recommendation': 'توصية ذكية',
      'toggle_balance_privacy': 'إخفاء/إظهار الرصيد',
      'saved': 'تم الحفظ بنجاح',
      'type': 'النوع',
      'view': 'عرض',
      'enter_name': 'أدخل الاسم',
      'enter_amount': 'أدخل المبلغ',
      'invalid_amount': 'مبلغ غير صحيح',
      'app_title': 'Follow My Life',
      'app_tagline': 'نظام الذكاء المالي',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'dashboard': 'لوحة التحكم',
      'home': 'الرئيسية',
      'activity': 'النشاط',
      'transactions': 'المعاملات المالية',
      'plan': 'الخطة المالية',
      'plans': 'خطط الشراء والادخار',
      'profile': 'الملف الشخصي',
      'debts': 'الديون والقروض',
      'forecast': 'التوقعات المالية',
      'calendar': 'التقويم المالي',
      'monthly_review': 'التقرير الشهري',
      'reports': 'التقارير والتحليلات',
      'categories': 'الفئات',
      'budgets': 'الميزانيات',
      'recurring': 'المدفوعات المتكررة',
      'sources': 'مصادر الأموال',
      'health_score': 'مؤشر الصحة المالية',
      'emergency_reserve': 'احتياطي الطوارئ',
      'net_worth': 'صافي الثروة',
      'total_balance': 'إجمالي الرصيد',
      'available_balance': 'الرصيد المتاح',
      'reserved_balance': 'الرصيد المحجوز',
      'safe_to_spend': 'المبلغ الآمن للإنفاق',
      'safe_to_spend_breakdown': 'تفاصيل المبلغ الآمن للإنفاق',
      'safe_to_spend_desc': 'المبلغ الآمن للإنفاق يوضح لك ما يمكنك إنفاقه اليوم بأمان دون التأثير على فواتيرك القادمة أو أهداف الادخار أو احتياطي الطوارئ.',
      'safe_to_spend_today': 'المبلغ الآمن للإنفاق اليوم',
      'money_coming': 'أموال قادمة',
      'money_going': 'مصاريف متوقعة',
      'recent_activity': 'النشاط الأخير',
      'view_all': 'عرض الكل',
      'accounts': 'حسابات',
      'expenses': 'المصاريف',
      'due_on': 'مستحق في',
      'add': 'إضافة',
      'add_income': 'إضافة دخل',
      'add_expense': 'إضافة مصروف',
      'transfer': 'تحويل',
      'add_source': 'إضافة مصدر مال',
      'add_category': 'إضافة فئة',
      'add_budget': 'إضافة ميزانية',
      'add_recurring': 'إضافة عملية متكررة',
      'add_purchase': 'إضافة شراء مخطط',
      'add_debt': 'إضافة دين / قرض',
      'i_owe': 'علَيّ ديون (الالتزامات)',
      'owed_to_me': 'مستحقات لي (الديون)',
      'total_debt_balance': 'إجمالي الديون المستحقة',
      'total_receivables': 'إجمالي مستحقاتك',
      'pay_back': 'سداد',
      'collect': 'تحصيل',
      'record_payment': 'تسجيل سداد دين',
      'record_collection': 'تسجيل تحصيل دين',
      'no_active_debts': 'لا توجد ديون نشطة',
      'no_pending_receivables': 'لا توجد مستحقات معلقة',
      'no_debts_desc': 'أنت لا تدين بأي أموال لأي شخص في الوقت الحالي.',
      'no_receivables_desc': 'لا أحد يدين لك بأي أموال حالياً.',
      'no_sources': 'لا توجد مصادر أموال',
      'no_sources_desc': 'أضف نقوداً كاش أو حساباً بنكياً أو محفظة لبدء التتبع.',
      'no_transactions': 'لا توجد معاملات بعد',
      'no_transactions_desc': 'سجل دخلك أو مصروفاتك لرؤية نشاطك المالي هنا.',
      'no_plans': 'لا توجد مشتريات مخططة',
      'no_plans_desc': 'خطط لذكاء استهلاكك القادم أو هدف الادخار.',
      'no_budgets': 'لم يتم تحديد ميزانيات',
      'no_budgets_desc': 'حدد حدود الإنفاق للفئات للتحكم بمصاريفك الشهري.',
      'no_categories': 'لا توجد فئات',
      'no_categories_desc': 'أنشئ فئات لتنظيم معاملتك المالية.',
      'no_recurring': 'لا توجد مدفوعات متكررة',
      'no_recurring_desc': 'أضف الاشتراكات أو الفواتير الدورية لإنشاء تتبع آلي.',
      'preferences': 'التفضيلات',
      'security': 'الأمان والقفل',
      'data': 'البيانات وإعادة الضبط',
      'language': 'اللغة',
      'theme': 'نمط العرض',
      'currency': 'العملة الرئيسية',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'النظام',
      'manage_categories': 'إدارة الفئات',
      'manage_budgets': 'إدارة الميزانيات',
      'manage_recurring': 'إدارة العمليات المتكررة',
      'app_lock': 'رمز PIN وبصمة الأصبع',
      'data_privacy': 'خصوصية البيانات',
      'backup_restore': 'النسخ الاحتياطي والاستعادة',
      'reset_data': 'إعادة ضبط كل البيانات',
      'search': 'بحث...',
      'all': 'الكل',
      'income': 'دخل',
      'expense': 'مصروف',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'submit': 'إرسال',
      'edit': 'تعديل',
      'delete': 'حذف',
      'due_date': 'تاريخ الاستحقاق',
      'amount': 'المبلغ',
      'note': 'ملاحظة',
      'description': 'الوصف',
      'category': 'الفئة',
      'source': 'الحساب / المصدر',
      'priority': 'الأولوية',
      'status': 'الحالة',
      'recalculate_balance': 'إعادة حساب الرصيد',
      'balance_recalculated': 'تمت إعادة حساب الرصيد بنجاح',
      'confirm_delete': 'تأكيد الحذف',
      'confirm_delete_msg': 'هل أنت متأكد من أنك تريد حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'something_went_wrong': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
      'cash': 'نقداً (كاش)',
      'bank_account': 'حساب بنكي',
      'e_wallet': 'محفظة إلكترونية',
      'income_source': 'مصدر دخل',
      'other': 'آخر',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'tomorrow': 'غداً',
      'this_month': 'هذا الشهر',
      'last_month': 'الشهر الماضي',
      'set_pin_title': 'تعيين رمز PIN الأمان',
      'enter_pin_title': 'أدخل رمز PIN',
      'confirm_pin_title': 'تأكيد رمز PIN الأمان',
      'pin_saved': 'تم تحديث رمز PIN',
      'pin_incorrect': 'رمز PIN غير صحيح.',
      'pin_too_many_attempts': 'تم تجاوز عدد المحاولات المسموح بها. تم حظر الدخول مؤقتاً.',
      'lockout_active': 'حظر الأمان موقتاً مفعل. يرجى الانتظار.',
      'auth_required_title': 'المصادقة مطلوبة',
      'auth_required_desc': 'الرجاء إدخال رمز PIN لتعديل إعدادات الأمان.',
      'color_preset': 'مظهر الألوان والتدرج',
      'theme_color': 'لوحة الألوان',
      'pin_disabled': 'تم إلغاء قفل PIN',
      'data_cleared': 'تم مسح كافة بيانات التطبيق بنجاح.',
      'virtual_splits': 'توزيع الراتب والأموال',
      'virtual_split': 'التقسيم الافتراضي',
      'create_split': 'إنشاء تقسيم افتراضي',
      'split_name': 'اسم التقسيم',
      'allocated': 'المخصص',
      'unallocated': 'غير المخصص',
      'original_balance': 'الرصيد المتاح الأصلي',
      'remaining_unallocated': 'المتبقي غير المخصص',
      'apply_split': 'تطبيق التقسيم',
      'confirm_apply_split': 'هل أنت متأكد من تطبيق هذا التقسيم الافتراضي؟ سيتم تسجيل معاملات حقيقية في سجل حساباتك.',
      'split_applied_success': 'تم تطبيق التقسيم الافتراضي بنجاح!',
      'split_already_applied': 'تم تطبيق هذا التقسيم الافتراضي بالفعل.',
      'insufficient_funds_split': 'الرصيد المتاح غير كافٍ لتطبيق هذا التقسيم.',
      'biometrics': 'المصادقة البيومترية (بصمة الأصبع / الوجه)',
      'enable_biometrics': 'تفعيل بصمة الأصبع / الوجه',
      'biometrics_not_available': 'المصادقة البيومترية غير متوفرة على هذا الجهاز.',
      'biometrics_failed': 'لم يتم التعرف على البصمة. حاول مجدداً أو استخدم رمز PIN.',
      'biometric_auth_reason': 'يرجى المصادقة لفتح تطبيق Follow My Life',
      'unlock': 'إلغاء قفل التطبيق',
      'total_planned_targets': 'إجمالي الأهداف المخططة',
      'items': 'عناصر',
      'reserved': 'المحجوز',
      'remaining': 'المتبقي',
      'emergency_reserve_target': 'هدف احتياطي الطوارئ',
      'emergency_reserve_desc': 'المبلغ الاحتياطي الموصى به: 3 إلى 6 أشهر من المصاريف الحيوية.',
      'can_buy_now': 'يمكن الشراء الآن بالرصيد المتاح',
      'needs_more': 'يحتاج إلى رصيد إضافي',
      'buy_now': 'شراء الآن',
      'reserve_funds': 'حجز أموال',
      'money_locations': 'أماكن تواجد الأموال',
      'reconciled': 'مستقر',
      'upcoming_obligations': 'الالتزامات القادمة',
      'no_recent_activity': 'لا يوجد نشاط حديث',
      'net_cash_flow': 'صافي التدفق النقدي',
      'required_monthly': 'المبلغ الشهري المطلوب',
      'est_completion': 'الإنجاز المتوقع',
      'feasibility': 'جدوى الخطة',
      'high_feasibility': 'سهلة التحقيق',
      'medium_feasibility': 'جهد متوسط',
      'low_feasibility': 'موعد صعب',
      'capacity_simulator': 'محاكي القدرة الادخارية',
      'simulate_monthly_savings': 'محاكاة الادخار الشهري',
      'smart_actions_title': 'المساعد المالي الذكي',
      'all_clear_title': 'كل الأمور ممتازة',
      'all_clear_desc': 'وضعك المالي مستقر وسليم جداً.',
      'fingerprint_enabled': 'تم تفعيل المصادقة بالبصمة',
      'fingerprint_disabled': 'تم تعطيل المصادقة بالبصمة',
      'profile_name_updated': 'تم تحديث اسم الملف الشخصي بنجاح',
      'language_updated': 'تم تحديث اللغة بنجاح',
      'theme_updated': 'تم تحديث المظهر بنجاح',
      'currency_updated': 'تم تحديث العملة بنجاح',
      'edit_profile_name': 'تعديل اسم الملف الشخصي',
      'export_backup': 'تصدير نسخة احتياطية',
      'import_backup': 'استيراد نسخة احتياطية',
      'backup_export_saved': 'تم حفظ النسخة الاحتياطية بنجاح.',
      'backup_imported': 'تمت استعادة البيانات بنجاح.',
      'setup_profile': 'إعداد الملف الشخصي',
      'pin_active': 'مفعّل (PIN)',
      'pin_off': 'غير مفعّل',
      'data_protected': 'محمي',
      'data_encrypted_local': 'البيانات مشفّرة محلياً على الجهاز.',
      'error_loading_profile': 'خطأ في تحميل الملف الشخصي',
      'enter_4_digit_pin': 'أدخل رمز PIN من 4 أرقام',
      'failed_load_summary': 'فشل في تحميل الملخص',
      'error_loading_transactions': 'خطأ في تحميل المعاملات',
      'monthly_financial_review': 'التقرير المالي الشهري',
      'monthly_review_summary': 'ملخص التقرير الشهري',
      'monthly_review_desc': 'تقييم شامل للتدفق النقدي ومعدل الادخار والصحة المالية.',
      'health_score_label': 'مؤشر الصحة',
      'total_income': 'إجمالي الدخل',
      'total_expenses': 'إجمالي المصاريف',
      'net_savings': 'صافي الادخار',
      'savings_rate': 'معدل الادخار',
      'error_loading_summary': 'خطأ في تحميل الملخص',
      'income_vs_expenses': 'الدخل مقابل المصاريف',
      'spending_by_category': 'المصاريف حسب الفئة',
      'no_category_data': 'لا توجد بيانات مصاريف لهذه الفترة.',
      'error_loading_categories': 'خطأ في تحميل الفئات',
      'this_year': 'هذه السنة',
      'vs_last_month': 'مقارنة بالشهر الماضي',
      'daily_budget': 'الميزانية اليومية',
      'days_left': 'أيام متبقية',
      'spending_pace': 'وتيرة الإنفاق',
      'on_track': 'على المسار الصحيح',
      'over_budget': 'تجاوز الميزانية',
      'under_budget': 'تحت الميزانية',
      'more_tools': 'المزيد',
      'salary_allocation': 'توزيع الراتب',
      'allocate_salary': 'توزيع الراتب',
      'fund_distribution': 'توزيع الأموال',
      'action_cash_deficit_title': 'خطر نفاذ السيولة النقدية',
      'action_cash_deficit_desc': 'الالتزامات القادمة تتجاوز الرصيد المتاح.',
      'action_budget_exceeded_title': 'تجاوز حد الميزانية',
      'action_budget_exceeded_desc': 'تجاوزت إحدى الفئات الحد المخصص لها.',
      'action_split_pending_title': 'توزيع الراتب قيد الانتظار',
      'action_split_pending_desc': 'لديك توزيعات جاهزة للتنفيذ.',
      'action_sub_renewal_title': 'تجديد اشتراك قادم',
      'action_plan_boost_title': 'تحسين ادخار الأهداف',
      'action_plan_boost_desc': 'تدفق نقدي ممتاز. يمكنك زيادة ادخار خططك المخططة.',
      'plan_name': 'اسم الخطة',
      'priority_low': 'منخفضة',
      'priority_medium': 'متوسطة',
      'priority_high': 'عالية',
      'edit_recurring': 'تعديل الدفعة المتكررة',
      'delete_recurring': 'حذف الدفعة المتكررة',
      'edit_category': 'تعديل الفئة',
      'delete_category': 'حذف الفئة',
      'edit_source': 'تعديل مصدر المال',
      'delete_source': 'حذف مصدر المال',
      'theme_mode': 'المظهر والسمة',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'system_mode': 'حسب النظام',
      'cash_flow_forecast': 'توقعات التدفق النقدي',
      'projected_balance': 'الرصيد المتوقع',
      'days': 'أيام',
      'net_change': 'صافي التغير',
      'forecast_timeline': 'الجدول الزمني للتوقعات',
      'no_movements': 'لا يوجد حركات مجدولة',
      'from': 'من',
      'to': 'إلى',
      'date': 'التاريخ',
      'note_optional': 'ملاحظة (اختياري)',
      'need_2_sources': 'تحتاج إلى مصادر مالية 2 على الأقل لتحويل الأموال',
      'please_select_both_sources': 'يرجى تحديد كلا المصدرين',
      'same_source_error': 'لا يمكن التحويل إلى نفس المصدر',
      'transaction_details': 'تفاصيل المعاملة',
      'record_linked_refund': 'تسجيل استرداد مرتبط',
      'delete_transaction_confirm': 'سيعيد هذا الإجراء تأثيره على رصيدك. هل أنت تأكد؟',
      'record_refund': 'تسجيل استرداد',
      'original_expense': 'المصروف الأصلي',
      'submit_refund': 'إرسال الاسترداد',
      'backup_json_desc': 'أنشئ نسخة احتياطية مشفرة بتنسيق JSON أو استعد من ملف.',
      'money_account': 'حساب المال',
      'income_origin': 'مصدر الدخل',
      'payee_merchant': 'المستفيد / التاجر',
      'no_description': 'بدون وصف',
      'source_reference': 'مرجع المصدر',
      'itemized_splits': 'التقسيمات المفصلة',
      'refund_amount': 'مبلغ الاسترداد',
      'estimated_cost': 'التكلفة التقديرية',
      'select_destination_source': 'يرجى تحديد مصدر الوجهة',
      'need_source_first': 'تحتاج إلى مصدر مال أولاً',
      'title_description': 'العنوان / الوصف',
      'to_source': 'إلى المصدر',
      'paid_from': 'مدفوع من',
      'what_was_this_for': 'ماذا كان هذا مقابل؟',
      'source_details': 'تفاصيل المصدر',
      'initial_balance': 'الرصيد الأولي',
      'subscription_bill_name': 'اسم الاشتراك/الفاتورة',
      'income_name': 'اسم الدخل',
      'auto_post_source': 'النشر التلقائي للمصدر (اختياري)',
      'none_remind_me': 'بدون (تذكيري)',
      'plan_capacity_simulator': 'محاكي قدرة الخطة',
      'simulator_desc': 'أدخل قدرتك الادخارية الشهرية لترى كيف يتم توزيعها على خططك النشطة.',
      'monthly_savings_capacity': 'القدرة الادخارية الشهرية',
      'simulate_capacity': 'محاكاة القدرة',
      'optimal_allocation': 'التوزيع الأمثل',
      'close': 'إغلاق',
      'delete_item_title': 'حذف العنصر',
      'delete_item_confirm': 'هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.',
      'item_deleted': 'تم حذف العنصر بنجاح',
      'item_not_found': 'العنصر غير موجود',
      'welcome_title': 'مرحباً بك في\nFollow My Life',
      'welcome_subtitle': 'مركز تحكمك الشخصي. لنبدأ بإعداد ملفك الشخصي.',
      'onboarding_name_label': 'ماذا نناديك؟',
      'get_started': 'ابدأ الآن',
      'unlocked': 'تم فتح القفل',
      'filter_all': 'الكل',
      'filter_ready': 'جاهز',
      'target_date_label': 'الهدف',
      'target_date_optional': 'تاريخ الهدف (اختياري)',
      'clear_date': 'مسح التاريخ',
      'error_loading_plans': 'خطأ في تحميل الخطط',
      'error_loading_debts': 'خطأ في تحميل الديون',
      'error_loading_recurring': 'خطأ في تحميل العمليات المتكررة',
      'error_loading_sources': 'خطأ في تحميل المصادر',
      'error_loading_budgets': 'خطأ في تحميل الميزانيات',
      'error_loading_splits': 'خطأ في تحميل التقسيمات',
      'reserved_amount': 'المبلغ المحجوز',
      'reserved_amount_updated': 'تم تحديث المبلغ المحجوز',
      'purchase_completed': 'تم إتمام الشراء!',
      'plan_updated': 'تم تحديث الخطة',
      'per_month': '/شهر',
      'plan_purchase': 'تخطيط شراء',
      'purchase_name_label': 'ماذا تريد أن تشتري؟',
      'create_budget': 'إنشاء ميزانية',
      'budget_name': 'اسم الميزانية',
      'budget_name_hint': 'مثال: البقالة، الترفيه',
      'limit_amount': 'المبلغ الأقصى',
      'period': 'الفترة',
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'link_category_optional': 'ربط بفئة (اختياري)',
      'none_general_budget': 'بدون (ميزانية عامة)',
      'i_owe_someone': 'أنا مدين لشخص',
      'someone_owes_me': 'شخص مدين لي',
      'debt_person_hint': 'مثال: كريم، قرض بنكي، أحمد',
      'principal_amount': 'المبلغ الأصلي',
      'repayment_date_label': 'تاريخ السداد المتوقع (اختياري)',
      'notes_optional': 'ملاحظات أو شروط (اختياري)',
      'debt_created': 'تم إنشاء سجل الدين/القرض',
      'income_origin_hint': 'مثال: راتب، عمل حر',
      'extra_details_hint': 'تفاصيل إضافية',
      'payee_hint': 'مثال: قهوة، بقالة',
      'source_name_hint': 'مثال: محفظتي، بنك BNA',
      'retry': 'إعادة المحاولة',
      'party_label': 'الطرف',
      'original_label': 'الأصلي',
      'remaining_label': 'المتبقي',
      'invalid_amount_source': 'يرجى إدخال مبلغ ومصدر صالحين',
      'debt_payment_recorded': 'تم تسجيل سداد الدين بنجاح!',
      'split_description': 'قم بتوزيع أموالك المتاحة مسبقاً على الفئات المستهدفة قبل الإنفاق.',
      'split_cancelled': 'تم إلغاء التقسيم الافتراضي',
      'split_exceeds_balance': 'إجمالي مبلغ التقسيم يتجاوز الرصيد المتاح!',
      'select_category_required': 'يرجى تحديد فئة لكل عنصر',
      'split_created': 'تم إنشاء التقسيم الافتراضي',
      'general': 'عام',
      'default_user': 'مستخدم',
      'forecast_in': 'وارد',
      'forecast_out': 'صادر',
      'upcoming_events': 'الأحداث المالية القادمة',
      'frequency': 'التكرار',
      'no_events_month': 'لا توجد أحداث مجدولة لهذا الشهر',
      'skip': 'تخطي',
      'next': 'التالي',
      'onboarding_slide1_title': 'الذكاء المالي الكامل',
      'onboarding_slide1_desc': 'إدارة النفقات والتأمين والحسابات محلياً بدون مشاركة بيانات سحابية.',
      'onboarding_slide2_title': 'التوزيع الذكي للأظرف',
      'onboarding_slide2_desc': 'خصص مدخراتك وأولوياتك مسبقاً قبل الإنفاق لضمان الأمان المالي.',
      'onboarding_slide3_title': 'التنبؤ والقدرة الشرائية',
      'onboarding_slide3_desc': 'محاكاة القدرة على تحقيق الأهداف ومراقبة توقعات الرصيد المستقبلي.',
      'onboarding_slide4_title': 'إعداد سجلّك المالي الخاص',
      'onboarding_slide4_desc': 'أدخل اسمك لفتح نظام التشغيل المالي الخاص بك.',
      'page_not_found_desc': 'الصفحة أو المسار المطلوب غير موجود أو تم نقله.',
      'simulation_calculated': 'تم تحديث محاكاة الخطة بنجاح.',
      'tmpl_salary_50_20_20_10': 'قاعدة الراتب 50/20/20/10',
      'tmpl_salary_50_20_20_10_desc': '50% الاحتياجات، 20% المدخرات، 20% الخطط والأهداف، 10% إنفاق حر',
      'tmpl_classic_50_30_20': 'القاعدة الكلاسيكية 50/30/20',
      'tmpl_classic_50_30_20_desc': '50% الاحتياجات الأساسية، 30% الرغبات الشخصية، 20% الادخار',
      'tmpl_monthly_essentials': 'نموذج الأساسيات الشهرية',
      'tmpl_monthly_essentials_desc': '40% الطعام والمشتريات، 30% الفواتير، 15% المواصلات، 15% الاحتياطي',
      'tmpl_emergency_first': 'أولوية احتياطي الطوارئ',
      'tmpl_emergency_first_desc': '50% صندوق الطوارئ، 30% تكاليف المعيشة، 20% إنفاق مرن',
      'tmpl_debt_paydown': 'تسديد الديون السريع',
      'tmpl_debt_paydown_desc': '40% سداد الديون، 40% مصاريف المعيشة، 10% الادخار، 10% احتياطي',
      'tmpl_wealth_growth': 'الاستثمار وبناء الثروة',
      'tmpl_wealth_growth_desc': '40% الاستثمار والنمو، 30% المصاريف الأساسية، 20% النقد الاحتياطي، 10% الترفيه',
      'tmpl_travel_vacation': 'ميزانية السفر والعطلات',
      'tmpl_travel_vacation_desc': '40% السكن والفنادق، 30% الطيران والنقل، 30% الأنشطة والمطاعم',
      'tmpl_student_freelancer': 'ميزانية الطلاب والمستقلين',
      'tmpl_student_freelancer_desc': '60% الأساسيات اليومية، 20% أدوات العمل والدراسة، 20% احتياطي المستقل',
      'cat_needs_essentials': 'الاحتياجات والأساسيات',
      'cat_savings_reserve': 'الادخار والاحتياطي',
      'cat_plans_goals': 'الخطط والأهداف',
      'cat_free_spending': 'الإنفاق الحر',
      'cat_essential_needs': 'الاحتياجات الأساسية',
      'cat_personal_wants': 'الرغبات الشخصية',
      'cat_savings_investments': 'الادخار والاستثمار',
      'cat_food_groceries': 'الطعام والمشتريات',
      'cat_utilities_bills': 'الفواتير والخدمات',
      'cat_transport_fuel': 'المواصلات والوقود',
      'cat_emergency_buffer': 'احتياطي الأمان',
      'cat_emergency_reserve': 'صندوق الطوارئ',
      'cat_fixed_living': 'المصاريف الثابتة',
      'cat_flexible_spending': 'الإنفاق المرن',
      'cat_debt_repayment': 'سداد الديون',
      'cat_living_essentials': 'أساسيات المعيشة',
      'cat_investments_growth': 'الاستثمار والنمو',
      'cat_core_expenses': 'النفقات الرئيسية',
      'cat_cash_reserve': 'الاحتياطي النقدي',
      'cat_lifestyle': 'أسلوب الحياة والترفيه',
      'cat_lodging_hotel': 'الإقامة والفنادق',
      'cat_flights_transit': 'الطيران والنقل',
      'cat_activities_dining': 'الأنشطة والمطاعم',
      'cat_basic_survival': 'الاحتياجات الحيوية',
      'cat_work_study_tools': 'أدوات العمل والدراسة',
      'cat_future_buffer': 'احتياطي المستقبل',
      'delete_transaction': 'حذف المعاملة',
      'split': 'تقسيم',
      'amount_positive': 'يجب أن يكون المبلغ أكبر من الصفر.',
      'saved_successfully': 'تم الحفظ بنجاح.',
      'capacity_summary': 'ملخص قدرة المحاكاة',
      'total_target_amount': 'إجمالي المستهدف للأهداف',
      'months_needed': 'الوقت المتوقع المطلوب',
      'fully_feasible': 'قابل للتحقيق 100% وممول بالكامل',
      'capacity_deficit': 'عجز جزئي في القدرة الإدخارية',
      'no_plans_to_simulate': 'لا توجد خطط شراء نشطة',
      'create_plan_first_desc': 'أنشئ خطة شراء لمتابعة أهدافك الحقيقية أو جرب محاكاة هدف تجريبي أدناه.',
      'simulate_sample_plan': 'محاكاة هدف تجريبي (100,000 د.ج)',
      'sample_plan_title': 'هدف إدخار تجريبي',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) => AppLocalizations.of(this).translate(key);
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
